# Generated by Django 5.2.4 on 2025-09-04 11:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('broker', '0009_intradaydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_fill', 'Order Fill'), ('price_alert', 'Price Alert'), ('trade_execution', 'Trade Execution'), ('margin_call', 'Margin Call'), ('account_update', 'Account Update'), ('system_message', 'System Message')], help_text='The type of trading event notification.', max_length=20)),
                ('content', models.TextField(help_text='The text content of the notification.')),
                ('price', models.DecimalField(blank=True, decimal_places=4, help_text='Price associated with the notification (e.g., alert price).', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('related_url', models.URLField(blank=True, help_text='URL to the relevant trade or account page.', null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Indicates whether the user has read the notification.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the notification was created.')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.instrumentdetails')),
                ('trade_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='broker.trade')),
            ],
            options={
                'verbose_name': 'Trading Notification',
                'verbose_name_plural': 'Trading Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
