# Generated by Django 5.2.4 on 2025-08-27 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlgoStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('support', models.FloatField()),
                ('resistance', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntrumentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intrument_key', models.CharField(max_length=200)),
                ('exchange_tokenk', models.CharField(max_length=200)),
                ('tradingsymbol', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('last_price', models.FloatField()),
                ('expiry', models.CharField(max_length=200)),
                ('strike', models.FloatField()),
                ('lot_size', models.FloatField()),
                ('intrument_type', models.CharField(max_length=200)),
                ('option_type', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField(unique=True)),
                ('access_token', models.CharField(max_length=200)),
                ('refresh_token', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart', models.CharField(max_length=200)),
                ('strike_price', models.FloatField()),
                ('option_chain_call_or_put', models.CharField(max_length=20)),
                ('order_type', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=200, unique=True)),
                ('buy_at', models.FloatField()),
                ('target', models.FloatField()),
                ('sell_at', models.FloatField()),
                ('trade_time', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('swing_strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.algostrategy')),
            ],
        ),
    ]
