# Generated by Django 5.2.4 on 2025-08-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_alter_token_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
