# Generated by Django 5.2.4 on 2025-08-27 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0004_alter_token_access_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='user',
            new_name='clinet_id',
        ),
    ]
