# Generated by Django 5.2.4 on 2025-08-28 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0005_rename_user_token_clinet_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intrumentdetails',
            old_name='intrument_key',
            new_name='instrument_key',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='clinet_id',
            new_name='client_id',
        ),
    ]
