# Generated by Django 5.2.4 on 2025-08-28 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0006_rename_intrument_key_intrumentdetails_instrument_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intrumentdetails',
            old_name='intrument_type',
            new_name='instrument_type',
        ),
    ]
