# Generated by Django 5.2.4 on 2025-08-28 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0007_rename_intrument_type_intrumentdetails_instrument_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IntrumentDetails',
            new_name='InstrumentDetails',
        ),
        migrations.RenameField(
            model_name='instrumentdetails',
            old_name='exchange_tokenk',
            new_name='exchange_token',
        ),
    ]
