# Generated by Django 5.2.4 on 2025-08-29 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0008_rename_intrumentdetails_instrumentdetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntradayData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.instrumentdetails')),
            ],
            options={
                'unique_together': {('instrument', 'datetime')},
            },
        ),
    ]
