# Generated by Django 5.2.4 on 2025-09-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('symbol', models.CharField(max_length=50)),
                ('expiry', models.DateField()),
                ('strike_price', models.FloatField()),
                ('instrument_type', models.CharField(choices=[('CE', 'Call Option'), ('PE', 'Put Option')], max_length=2)),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('order_type', models.CharField(choices=[('MARKET', 'MARKET'), ('LIMIT', 'LIMIT'), ('SL', 'SL'), ('SL-M', 'SL-M')], max_length=10)),
                ('product_type', models.CharField(choices=[('I', 'Intraday'), ('D', 'Delivery'), ('MTF', 'Margin')], max_length=3)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PLACED', 'Placed'), ('COMPLETE', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('filled_quantity', models.IntegerField(default=0)),
                ('average_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
